# Generated by Django 3.0.5 on 2020-05-04 10:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mylessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='наименование')),
                ('school', models.CharField(max_length=100, verbose_name='организация')),
                ('annotation', models.TextField(verbose_name='аннотация')),
                ('data_create', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
