# Generated by Django 3.0.5 on 2020-06-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylessons',
            name='moneys',
            field=models.TextField(default='', verbose_name='Маржа'),
        ),
    ]
